### ISSUE TITLE
Transparency in textures is changed to black

### ISSUE THREAD

**Issue by ghost** [rodrigojxd/PCTexture2PE#3]
Resource Pack: https://mods.curse.com/texture-packs/minecraft/220720-invictus-vanilla

### MCPE

![minecraft_ windows 10 edition 1_8_2017 2_20_22 am](https://cloud.githubusercontent.com/assets/7173984/21748107/e074f0a8-d549-11e6-8caa-ecba53753bc5.png)

### MC 1.11.2
![minecraft 1 11 2 1_8_2017 2_22_51 am](https://cloud.githubusercontent.com/assets/7173984/21748108/e436d58a-d549-11e6-81f4-5ef3213f9941.png)

**Comment by rodrigojxd** [comment]
This is a problem with the MCPE/win10 edition. It does not support mobs skins with transparency (at least not all). So I can not do anything about it. You should then report it to mojang if you want this corrected. Thanks for your reports though.
