### ISSUE TITLE
Grass animations are lost

### ISSUE THREAD

**Issue by ghost** [rodrigojxd/PCTexture2PE#4]
Texture pack: https://mods.curse.com/texture-packs/minecraft/220720-invictus-vanilla

### MCPE

https://youtu.be/3GjtsFzhIdY

![giphy](https://cloud.githubusercontent.com/assets/7173984/21748155/4c5f975e-d54b-11e6-88ff-e0e49bf23bf2.gif)

### MC 1.11.2

![giphy 1](https://cloud.githubusercontent.com/assets/7173984/21748157/4f9ed6c8-d54b-11e6-93ca-625723091431.gif)

https://youtu.be/Ip3r_4mzCq8

**Comment by rodrigojxd** [comment]
Sorry, but for now the program does not convert animations. Maybe in the future.
