### ISSUE TITLE
Minecraft 1.2 has changed the add-on format

### ISSUE THREAD

**Issue by ghost** [rodrigojxd/PCTexture2PE#6]
MCPE 1.0.4 brings the following changes:

* A new add-on format, see the vanilla template at https://minecraft.net/en-us/addons/ to see the changes
* The models for the Shulker and Ender Dragon can now be edited using Add-Ons

**Comment by rodrigojxd** [comment]
Thx. I implemented the new format. Models do not matter because MCPC does not support custom mobs models. I will release the new version soon.

**Comment by inxomnyaa** [comment]
The addon data is updated again, would you change it to the 1.2 addons?

**Comment by ghost** [comment]
Note that they no longer refer to MCPE as it is and is now considered the canonical minecraft.

**Comment by inxomnyaa** [comment]
aka Bedrock codebase aka united aka buggy-and-crappy aka money mine aka minecraftpe.xxx as in the android source and MCPE in the network layer.
